# Generated by Django 3.1.7 on 2021-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=200, unique=True)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=15)),
                ('Date', models.DateField(help_text='date when the squirrel is found')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='the age of the squirrel', max_length=15)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='primary fur color', max_length=200)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='the Location of the squirrel', max_length=15)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(blank=True, null=True)),
                ('Chasing', models.BooleanField(blank=True, null=True)),
                ('Climbing', models.BooleanField(blank=True, null=True)),
                ('Eating', models.BooleanField(blank=True, null=True)),
                ('Foraging', models.BooleanField(blank=True, null=True)),
                ('Other_Activities', models.CharField(blank=True, max_length=200, null=True)),
                ('Kuks', models.BooleanField(blank=True, help_text='Squirrel was heard kukking.', null=True)),
                ('Quaas', models.BooleanField(blank=True, help_text='Squirrel was heard quaaing.', null=True)),
                ('Moans', models.BooleanField(blank=True, help_text='Squirrel was heard moaning.', null=True)),
                ('Tail_Flags', models.BooleanField(blank=True, help_text='Squirrel was seen flagging its tail.', null=True)),
                ('Tail_Twitches', models.BooleanField(blank=True, help_text='Squirrel was seen twitching its tail.', null=True)),
                ('Approaches', models.BooleanField(blank=True, help_text='Squirrel was seen approaching human.', null=True)),
                ('Indifferent', models.BooleanField(blank=True, help_text='Squirrel was indifferent to human presence.', null=True)),
                ('Runs_From', models.BooleanField(blank=True, help_text='Squirrel was seen running from humans, seeing them as a threat.', null=True)),
            ],
        ),
    ]
