# Generated by Django 3.1.7 on 2021-04-15 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20210412_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='the age of the squirrel', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='the Location of the squirrel', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='primary fur color', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Format: <Hectare ID>-<AM/PM>-<4-digit Date>-<Hectare Squirrel Number>.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ID', message='Please enter in the format of: <Hectare ID>-<AM/PM>-<4-digit Date>-<Hectare Squirrel Number>.', regex='^\\d{1,2}[A-Z]{1}-[A-Z]{2}-\\d{4}-\\d{2}$')]),
        ),
    ]
