# Generated by Django 3.1.7 on 2021-04-15 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20210415_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Format Example: 37F-PM-1014-03', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ID', message='Please enter in the format of: <Hectare ID>-<AM/PM>-<4-digit Date>-<Hectare Squirrel Number>.', regex='^\\d{1,2}[A-Z]{1}-[A-Z]{2}-\\d{4}-\\d{2}$')]),
        ),
    ]
