# Generated by Django 3.1.7 on 2021-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20210412_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(blank=True, help_text='Squirrel was seen approaching human.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(blank=True, help_text='Squirrel was indifferent to human presence.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(blank=True, help_text='Squirrel was heard kukking.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(blank=True, help_text='Squirrel was heard moaning.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(blank=True, help_text='Squirrel was heard quaaing.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(blank=True, help_text='Squirrel was seen running from humans, seeing them as a threat.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(blank=True, help_text='Squirrel was seen flagging its tail.', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(blank=True, help_text='Squirrel was seen twitching its tail.', null=True),
        ),
    ]
